"""Resolve before mint: what must be true before a new entity may exist, and the page it becomes.

Pure functions of a proposal and a registry — a refusal costs no git, no network, no cleanup.
The steward authors the identity metadata (`entity_type`, `aliases`, `role`); the agent's outcome
is name-only — agent-drafted aliases would invite rubber-stamping. Collision is asked of the
REGISTRY through `normalize` ("would these two ever be confused?"), never of bytes, over all
three identity inputs: the id (registry key), the name (title, filename, wikilink target) and
every alias (a spelling that silently reassigns mentions).

The gate is only as strong as what it inspects reaching the registry unchanged: the registry is
regenerated by PARSING THE PAGE BACK, so an alias interpolated with an f-string
(`--aliases 'x", "Jordan Reyes'`) passes the gate as ONE alias and parses back as TWO — one thing
under several identities, delivered through the gate. Hence two defence layers with no shared
mechanism: identity inputs are refused on forbidden characters (`_clean_name`, `_clean_aliases`),
AND `render_page` serializes every steward-authored value through `_yaml_str`. Either alone
closes the chain; only both survive somebody later relaxing one of them.
"""
import re
from dataclasses import dataclass

from stigmergy.entities import generator
from stigmergy.entities.errors import CollisionError, EntityError
from stigmergy.kernel.registry import Registry

# `type: entity` is fixed by the zone (`wiki/entities` accepts `entity` alone; `customer`/
# `product` are entity KINDS, carried as the registry's `type`). `status: developing` — evergreen
# is earned by staying current, never by being new.
PAGE_TYPE = "entity"
PAGE_STATUS = "developing"

# Re-exported from the generator rather than re-listed, so the value a page is written with and
# the value the registry is generated with can never be two different vocabularies.
ENTITY_TYPES = generator.ENTITY_TYPES

MAX_NAME_CHARS = 80
MAX_ROLE_CHARS = 200
MAX_ALIASES = 12

# A title becomes a FILENAME (`wiki/entities/<title>.md`) and a wikilink target: path separators
# plus the shell/YAML metacharacters that would need quoting in a link. An ALIAS is held to the
# same set — same matcher, same frontmatter.
_FORBIDDEN_IN_NAME = set('/\\:*?"<>|[]#^')

# The only subset a `role` is held to: `role` is a sentence, not an identity, so only the
# serialization-breaking characters are refused (`_yaml_str` escapes regardless; this keeps the
# validator and the writer two defences rather than one). Spelled out, never intersected with the
# set above — an intersection would silently go EMPTY if that set were narrowed, the one way a
# defence-in-depth layer can vanish without a visible diff.
_YAML_UNSAFE = frozenset('"\\')

# `created`/`updated` are written as bare YAML dates (quoting would change their type against
# every hand-authored page). A bare scalar cannot be escaped, so the value is CONSTRAINED instead.
_ISO_DATE_RE = re.compile(r"\A\d{4}-\d{2}-\d{2}\Z")


@dataclass(frozen=True)
class Proposal:
    """A validated identity, ready to be minted. Constructed only by `prepare`."""
    canonical_id: str
    name: str
    entity_type: str
    aliases: tuple[str, ...]
    role: str = ""

    @property
    def relpath(self) -> str:
        return f"{generator.ENTITIES_RELDIR}/{self.name}.md"


def _clean_name(name: str) -> str:
    value = " ".join(str(name or "").split())
    if not value:
        raise EntityError("--name is empty — an entity is a name before it is anything else")
    if len(value) > MAX_NAME_CHARS:
        raise EntityError(
            f"--name is {len(value)} characters (max {MAX_NAME_CHARS}) — it becomes a page title, "
            f"a filename and a wikilink target, so a name this long is a sentence rather than an "
            f"identity")
    bad = sorted(_FORBIDDEN_IN_NAME & set(value))
    if bad:
        raise EntityError(
            f"--name contains {', '.join(repr(c) for c in bad)}, which cannot appear in an entity "
            f"name — the name IS the filename ({generator.ENTITIES_RELDIR}/<name>.md) and the "
            f"wikilink other pages resolve it by")
    if value.startswith("."):
        raise EntityError("--name starts with '.', which would make a hidden file rather than a page")
    return value


def prepare(*, canonical_id: str, name: str, entity_type: str, aliases=(), role: str = "",
            registry: Registry, existing_pages=()) -> Proposal:
    """Validate a proposed identity against everything already registered. Raises, or returns it.

    Pure: `registry` and `existing_pages` are values, not a repo, so the CLI cannot accidentally
    check against a different registry than the one the commit will regenerate from.
    """
    name = _clean_name(name)
    entity_type = str(entity_type or "").strip().lower()
    if entity_type not in ENTITY_TYPES:
        raise EntityError(
            f"--type {entity_type!r} is not one of the entity types the page contract declares "
            f"({', '.join(ENTITY_TYPES)}) — it is written to the page's `entity_type` field and "
            f"becomes the registry's `type`, which the graph build resolves mentions with")

    derived_id = generator.canonical_id_for(name)
    declared_id = str(canonical_id or "").strip()
    if declared_id != derived_id:
        raise EntityError(
            f"--id {declared_id!r} is not the id this entity would have: {generator.REGISTRY_RELPATH} "
            f"is DERIVED from the entity pages, and the id of a page titled {name!r} is always "
            f"{derived_id!r} (the slug of its title). An id nobody can regenerate would survive "
            f"exactly until the next `{generator.FIX_COMMAND}` and then vanish, so it is refused "
            f"here instead of stored. Pass --id {derived_id} to confirm, or choose a different "
            f"--name")

    cleaned_aliases = _clean_aliases(aliases, name=name)
    _refuse_collisions(canonical_id=derived_id, name=name, aliases=cleaned_aliases,
                       registry=registry, existing_pages=existing_pages)
    return Proposal(canonical_id=derived_id, name=name, entity_type=entity_type,
                    aliases=cleaned_aliases, role=_clean_role(role))


def _clean_aliases(aliases, *, name: str) -> tuple[str, ...]:
    """De-duplicated, order-preserving, never an alias for the name itself, and held to the name's
    own character set.

    An alias equal to the title is dropped, not refused — `load_registry` indexes the name anyway.
    A FORBIDDEN CHARACTER is refused, naming it: an alias carrying `"` closes the frontmatter
    string it is written into and smuggles a second, unchecked alias into the registry (module
    docstring). Stated on the alias itself so it holds no matter what later renders it.
    """
    out, seen = [], {generator.canonical_id_for(name)}
    for alias in aliases or ():
        value = " ".join(str(alias or "").split())
        if not value:
            continue
        bad = sorted(_FORBIDDEN_IN_NAME & set(value))
        if bad:
            raise EntityError(
                f"the alias {value!r} contains {', '.join(repr(c) for c in bad)}, which cannot "
                f"appear in an entity name or in an alias for one — an alias is a spelling the "
                f"registry resolves to this entity and a wikilink other pages reach it by, and "
                f"{', '.join(repr(c) for c in bad)} would have to be quoted or escaped to be "
                f"either. Drop it, or split this into separate --aliases values")
        key = generator.canonical_id_for(value)
        if not key or key in seen:
            continue
        seen.add(key)
        out.append(value)
    if len(out) > MAX_ALIASES:
        raise EntityError(
            f"{len(out)} aliases were given (max {MAX_ALIASES}) — every alias is a spelling that "
            f"silently reassigns mentions to this entity, so a long list is a merge decision "
            f"rather than a birth")
    return tuple(out)


def _clean_role(role) -> str:
    """One line about the entity, collapsed and clipped — never a YAML escape.

    Held to `_YAML_UNSAFE` only (the constant carries the argument). `_yaml_str` is what makes
    the value survive verbatim; this refusal exists so the page stays safe if some future writer
    stops escaping.
    """
    value = " ".join(str(role or "").split())[:MAX_ROLE_CHARS]
    bad = sorted(_YAML_UNSAFE & set(value))
    if bad:
        raise EntityError(
            f"--role contains {', '.join(repr(c) for c in bad)}, which cannot appear in the "
            f"page's `role` field — it is written into the frontmatter, where those characters "
            f"delimit and escape the value rather than being part of it. Rephrase the line "
            f"without them (single quotes are fine)")
    return value


def _refuse_collisions(*, canonical_id: str, name: str, aliases, registry: Registry,
                       existing_pages) -> None:
    """The gate itself. Names WHICH input collided and WHICH entry it collided with.

    Ordered name -> id -> aliases: the id is DERIVED from the name, so a name collision collides
    on both, and reporting it as `--id` would misname the problem. `--id` then only fires when a
    DIFFERENT name slugs onto a taken id — the case where the id really is the problem.
    """
    for label, value in [("--name", name), ("--id", canonical_id),
                         *[("an alias", alias) for alias in aliases]]:
        hit = registry.canonical_id(value)
        if not hit:
            continue
        entry = registry.entities.get(hit, {})
        listed = ", ".join(entry.get("aliases") or ()) or "none"
        raise CollisionError(
            f"{value!r} (given as {label}) already resolves to the registered entity {hit!r} "
            f"(name: {entry.get('name')}, type: {entry.get('type')}, aliases: {listed}). If this "
            f"is the same thing, point the capture at the existing entity instead of minting a "
            f"second one — requeue it, or answer its ask-back naming {entry.get('name')!r}. If it "
            f"genuinely is a different one, pick an id, name or alias that does not collide and "
            f"try again")

    # The FILE check, beside the registry check: a page can exist while the registry does not know
    # it (drift, a hand-written page, a half-finished approval) — two files, one identity, nothing
    # refusing it. Case-insensitive because the knowledge repo's linter treats duplicate basenames
    # case-insensitively.
    wanted = f"{name}.md".lower()
    for relpath in existing_pages or ():
        if relpath.rsplit("/", 1)[-1].lower() == wanted:
            raise CollisionError(
                f"{relpath} already exists, so a page for {name!r} is already in the knowledge "
                f"repo even though {generator.REGISTRY_RELPATH} does not register it. That "
                f"disagreement is drift, not a free slot: run `{generator.FIX_COMMAND} --check` to "
                f"see it, and register or rename the existing page rather than writing a second "
                f"one beside it")


def recheck(proposal: Proposal, *, registry: Registry, existing_pages=()) -> None:
    """Re-run the gate for an ALREADY-VALIDATED proposal against a registry that has moved
    (between `prepare` and the push, `origin/main` can gain an entity nobody had seen).

    Same function, `_refuse_collisions`, so the two answers can never come from two
    implementations of "collides". Not a second `prepare`: only the world-dependent part is
    re-asked. The caller decides what `registry`/`existing_pages` mean — the retry path passes
    everything EXCEPT this proposal's own entity, since by then the page is committed and an
    unfiltered view would collide with itself.
    """
    _refuse_collisions(canonical_id=proposal.canonical_id, name=proposal.name,
                       aliases=proposal.aliases, registry=registry,
                       existing_pages=existing_pages)


# ── the page ──────────────────────────────────────────────────────────────────────────────────
def render_page(template: str, proposal: Proposal, *, today: str) -> str:
    """Materialize `ops/templates/entity.md` for this proposal.

    The template is read from the repo, never reproduced here — an edit to it reaches minted
    pages without a platform release. Only the frontmatter is rewritten, line by line (a YAML
    round-trip would reformat a block humans diff); the BODY stays as the template wrote it, a
    stub the steward fills in. Every human-authored value goes through `_yaml_str`, none through
    an f-string (module docstring).
    """
    front, body = _split(template)
    today = _clean_today(today)
    fields = {
        "type": PAGE_TYPE,
        "title": _yaml_str(proposal.name),
        "entity_type": proposal.entity_type,
        "role": _yaml_str(proposal.role),
        "status": PAGE_STATUS,
        "aliases": "[" + ", ".join(_yaml_str(a) for a in proposal.aliases) + "]",
        "created": today,
        "updated": today,
        "tags": f"[entity, {proposal.entity_type}]",
        # The page's OWN registry id, written explicitly rather than left to the template's
        # literal `[]`: under the page contract `[]` reads as a checked, explicit company-wide
        # scope, so leaving it would assert the wrong anchor on the one page type whose job is to
        # BE an entity.
        "entity": f"[{_yaml_str(proposal.canonical_id)}]",
        "related": "[]",
        "sources": "[]",
    }
    rendered = _rewrite_frontmatter(front, fields)
    body = body.replace("<Entity Name>", proposal.name)
    return f"---\n{rendered}\n---\n{body}"


_PLACEHOLDER_PREFIX = "<"


def _yaml_str(value) -> str:
    """One double-quoted YAML scalar that reads back as exactly `value`.

    Hand-written rather than `yaml.dump`ed because the frontmatter is rewritten LINE BY LINE and
    a dumper works on documents. Three escape classes: `\\` and `"` close or extend the scalar; a
    CONTROL character is forbidden raw in YAML's printable set, so an unescaped one makes PyYAML
    refuse the whole page — and `--role`/`--name` collapse whitespace but not `\\x1b`.
    """
    out = ['"']
    for char in str(value):
        if char in ("\\", '"'):
            out.append("\\" + char)
        elif char < " " or char == "\x7f":
            out.append(f"\\x{ord(char):02x}")
        else:
            out.append(char)
    out.append('"')
    return "".join(out)


def _clean_today(today) -> str:
    """The `created`/`updated` value, refused unless it is a bare ISO date.

    The one field that CANNOT be quoted: hand-authored pages write it unquoted (a YAML date), and
    `_yaml_str`ing it would change its type on minted pages only. A value that cannot be escaped
    is constrained instead — otherwise `--today` is a line-oriented write into the frontmatter.
    """
    value = str(today or "").strip()
    if not _ISO_DATE_RE.match(value):
        raise EntityError(
            f"--today {value!r} is not a date — it is written into the page's `created` and "
            f"`updated` fields as a bare YAML date, so it must be exactly YYYY-MM-DD")
    return value


def _split(template: str) -> tuple[str, str]:
    if not template.startswith("---"):
        raise EntityError(
            f"{generator.ENTITIES_RELDIR}'s template (ops/templates/entity.md) has no frontmatter "
            f"block, so there is nothing to fill in — a new entity page is the template with its "
            f"identity fields written, and this one cannot be read")
    parts = template.split("\n")
    for i in range(1, len(parts)):
        if parts[i].strip() == "---":
            return "\n".join(parts[1:i]), "\n".join(parts[i + 1:])
    raise EntityError("ops/templates/entity.md has a frontmatter block that is never closed")


def _rewrite_frontmatter(front: str, fields: dict) -> str:
    """Replace each declared key's value in place; append the ones the template does not carry.

    In place, so the template's own key ORDER and comments survive the way hand-authored pages
    have them. Trailing comments on the keys this writes are dropped: they are instructions to a
    human filling the template in, and the value is now filled.
    """
    written, out = set(), []
    for line in front.split("\n"):
        key = line.split(":", 1)[0].strip() if ":" in line and not line[:1].isspace() else ""
        if key in fields and key not in written:
            out.append(f"{key}: {fields[key]}")
            written.add(key)
        else:
            out.append(line)
    for key, value in fields.items():
        if key not in written:
            out.append(f"{key}: {value}")
    return "\n".join(line for line in out if line.strip()).strip("\n")


def commit_message(proposal: Proposal, *, submission_id: int | None = None,
                   trailer: str = "") -> str:
    """The one commit that carries the page and the regenerated registry.

    Conventional-commit shaped like the librarian's own, so the history reads in one dialect. The
    capture is named when there is one — the audit trail from an entity's birth back to the
    material that prompted it. `trailer` (e.g. `"Approved-by: ..."`) is appended as its own
    paragraph when non-empty, so `git log` on an App-authored mint still answers "who approved
    this identity" with a human; empty by default, keeping a steward's own commit byte-identical.
    """
    body = (f"Approved by a steward from capture #{submission_id}."
            if submission_id else "Created by a steward.")
    message = (f"feat(entity): add {proposal.name}\n\n{body}\n\n"
              f"Registry regenerated from {generator.ENTITIES_RELDIR}/ in the same commit.\n")
    if trailer:
        message += f"\n{trailer}\n"
    return message
