"""Resolve before mint: what has to be true before a new entity may exist, and the page it becomes.

Everything this module does happens BEFORE anything is written — the validation is a pure function
of a proposal and a registry, so the refusal a steward sees costs no git, no network and no
cleanup, and can be exercised without a clone at all.

**The steward authors the identity metadata, not the agent.** The agent's outcome schema is
name-only: it says "I cannot place this, and the name is X". `entity_type`, `aliases` and `role`
arrive as flags typed by a human with the material on screen. Agent-drafted aliases would invite
rubber-stamping, which is the failure mode a governance gate exists to prevent — a gate everybody
clicks through is a log entry, not a gate.

**What "collides" means, and why it is asked of the REGISTRY rather than of a string.**

`Registry.canonical_id` resolves a spelling through `normalize` — accents folded, case folded,
punctuation and legal suffixes stripped — which is the same matcher the graph build and the
anchoring gate use. So asking it "does this name already resolve?" asks the question that actually
matters ("would these two ever be confused?") rather than the one a string comparison can answer
("are these bytes equal?"). "Acme Corp" collides with a registered "Acme"; `northwind-slides`
does not collide with `Northwind Group` by bytes and does by nothing — which is why the FILE
check below exists beside the registry check, and why the two are reported separately.

Three inputs are checked, because each one is a different way to end up with two identities for
one thing:

- the **id** is the registry key and the graph's join column;
- the **name** is the page title, the wikilink target and the filename;
- an **alias** is a spelling that RESOLVES to the entity, so an alias colliding with another
  entity's name silently reassigns every mention of it.

**And the gate is only as strong as what it inspects reaches the registry unchanged.**

The registry is regenerated by PARSING THE PAGE BACK, so the identity that lands in
`ops/entity-registry.json` is whatever the YAML reader makes of the frontmatter — not the value
`_refuse_collisions` was handed. Interpolate an alias into the page with an f-string and those two
come apart: `--aliases 'x", "Jordan Reyes'` passes the gate as ONE alias nobody has registered and
comes back out of the parser as TWO, the second of them a registered name the gate would have
refused. `by_alias` is last-wins, so every later capture mentioning that name anchors to the wrong
entity — the exact "Acme / ACME Corp / acme-client" failure governed birth exists to prevent,
delivered *through* the gate, and invisible to the knowledge repo's registry linter because the
page and the registry agree with each other perfectly.

The defence is **two layers that do not share a mechanism**, because validation and serialization
fail in different ways: identity inputs are refused when they carry a character a name may not
carry (`_clean_name`, `_clean_aliases`), AND `render_page` serializes every steward-authored value
through `_yaml_str` rather than trusting that the validator caught everything. Either alone closes
that chain; only both survive somebody later relaxing one of them.
"""
import re
from dataclasses import dataclass

from stigmergy.entities import generator
from stigmergy.entities.errors import CollisionError, EntityError
from stigmergy.kernel.registry import Registry

# The page contract's own field values for a new entity page. `type: entity` is fixed by the zone
# (`wiki/entities` accepts `entity` alone — `customer`/`product` are entity KINDS rather than page
# types, and the registry already carries `type` per entity); `status: developing` is the
# template's default and the honest one — a just-born entity has a steward, not a track record,
# and `evergreen` is earned by staying current, never by being new.
PAGE_TYPE = "entity"
PAGE_STATUS = "developing"

# What the template's own comment declares (`ops/templates/entity.md`). Re-exported from the
# generator rather than re-listed, so the value a page is written with and the value the registry
# is generated with can never be two different vocabularies.
ENTITY_TYPES = generator.ENTITY_TYPES

MAX_NAME_CHARS = 80
MAX_ROLE_CHARS = 200
MAX_ALIASES = 12

# A title becomes a FILENAME (`wiki/entities/<title>.md`) and a wikilink target. These are the
# characters that would make it one or the other but not both — path separators, and the shell/YAML
# metacharacters that would need quoting in a link. An ALIAS is held to the same set: it is a
# spelling of the name, resolved by the same matcher and written to the same frontmatter, so a
# character a name may not carry is one an alias meaning that name may not carry either.
_FORBIDDEN_IN_NAME = set('/\\:*?"<>|[]#^')

# The subset of the above that would break the SERIALIZATION rather than the identity, and the only
# subset a `role` is held to. `role` is a sentence about the entity, not an identity — refusing a
# colon or a bracket there would fail `--role "CTO: platform"` for no reason anyone could act on,
# and the rule that a refusal must name its mechanism cuts both ways: a refusal a steward cannot
# understand is a refusal they route around. Serialization is `_yaml_str`'s job regardless;
# this exists so the validator and the writer are still two defences rather than one. Spelled out
# rather than intersected with the set above: an intersection would silently go EMPTY if that set
# were ever narrowed, which is the one way a defence-in-depth layer can disappear without a diff
# that looks like it removed anything.
_YAML_UNSAFE = frozenset('"\\')

# `created`/`updated` come from `--today`, an injectable clock, and go into the frontmatter as bare
# YAML scalars (dates, not strings — quoting them would change their type against every
# hand-authored page). A bare scalar cannot be escaped, so the value is CONSTRAINED instead: the
# one shape a date may have. Same defect class as the alias chain above, closed the only way an
# unquoted field can be.
_ISO_DATE_RE = re.compile(r"\A\d{4}-\d{2}-\d{2}\Z")


@dataclass(frozen=True)
class Proposal:
    """A validated identity, ready to be minted. Constructed only by `prepare`."""
    canonical_id: str
    name: str
    entity_type: str
    aliases: tuple[str, ...]
    role: str = ""

    @property
    def relpath(self) -> str:
        return f"{generator.ENTITIES_RELDIR}/{self.name}.md"


def _clean_name(name: str) -> str:
    value = " ".join(str(name or "").split())
    if not value:
        raise EntityError("--name is empty — an entity is a name before it is anything else")
    if len(value) > MAX_NAME_CHARS:
        raise EntityError(
            f"--name is {len(value)} characters (max {MAX_NAME_CHARS}) — it becomes a page title, "
            f"a filename and a wikilink target, so a name this long is a sentence rather than an "
            f"identity")
    bad = sorted(_FORBIDDEN_IN_NAME & set(value))
    if bad:
        raise EntityError(
            f"--name contains {', '.join(repr(c) for c in bad)}, which cannot appear in an entity "
            f"name — the name IS the filename ({generator.ENTITIES_RELDIR}/<name>.md) and the "
            f"wikilink other pages resolve it by")
    if value.startswith("."):
        raise EntityError("--name starts with '.', which would make a hidden file rather than a page")
    return value


def prepare(*, canonical_id: str, name: str, entity_type: str, aliases=(), role: str = "",
            registry: Registry, existing_pages=()) -> Proposal:
    """Validate a proposed identity against everything already registered. Raises, or returns it.

    Pure: `registry` and `existing_pages` are values, not a repo, so the whole of resolve-before-mint
    is testable without git and the CLI cannot accidentally check against a different registry than
    the one the commit will regenerate from.
    """
    name = _clean_name(name)
    entity_type = str(entity_type or "").strip().lower()
    if entity_type not in ENTITY_TYPES:
        raise EntityError(
            f"--type {entity_type!r} is not one of the entity types the page contract declares "
            f"({', '.join(ENTITY_TYPES)}) — it is written to the page's `entity_type` field and "
            f"becomes the registry's `type`, which the graph build resolves mentions with")

    derived_id = generator.canonical_id_for(name)
    declared_id = str(canonical_id or "").strip()
    if declared_id != derived_id:
        raise EntityError(
            f"--id {declared_id!r} is not the id this entity would have: {generator.REGISTRY_RELPATH} "
            f"is DERIVED from the entity pages, and the id of a page titled {name!r} is always "
            f"{derived_id!r} (the slug of its title). An id nobody can regenerate would survive "
            f"exactly until the next `{generator.FIX_COMMAND}` and then vanish, so it is refused "
            f"here instead of stored. Pass --id {derived_id} to confirm, or choose a different "
            f"--name")

    cleaned_aliases = _clean_aliases(aliases, name=name)
    _refuse_collisions(canonical_id=derived_id, name=name, aliases=cleaned_aliases,
                       registry=registry, existing_pages=existing_pages)
    return Proposal(canonical_id=derived_id, name=name, entity_type=entity_type,
                    aliases=cleaned_aliases, role=_clean_role(role))


def _clean_aliases(aliases, *, name: str) -> tuple[str, ...]:
    """De-duplicated, order-preserving, never an alias for the name itself, and held to the name's
    own character set.

    An alias equal to the title is dropped rather than refused: `load_registry` indexes the name
    anyway, so it resolves identically, and the knowledge repo's linter reports a self-alias as a
    finding. Refusing a harmless redundancy would fail a steward's command over something the tool
    can simply be right about.

    A FORBIDDEN CHARACTER is the opposite case and is refused, naming the character. An alias is
    an identity input and is held to `_clean_name`'s own rule, and the reason is not cosmetic: an
    alias carrying `"` closes the frontmatter string it is written into and smuggles a second,
    unchecked alias into the registry (module docstring). The rule is stated on the alias itself
    rather than on the rendered page so it holds no matter what later renders it — a registry
    entry, a wikilink, a linter's alias table.
    """
    out, seen = [], {generator.canonical_id_for(name)}
    for alias in aliases or ():
        value = " ".join(str(alias or "").split())
        if not value:
            continue
        bad = sorted(_FORBIDDEN_IN_NAME & set(value))
        if bad:
            raise EntityError(
                f"the alias {value!r} contains {', '.join(repr(c) for c in bad)}, which cannot "
                f"appear in an entity name or in an alias for one — an alias is a spelling the "
                f"registry resolves to this entity and a wikilink other pages reach it by, and "
                f"{', '.join(repr(c) for c in bad)} would have to be quoted or escaped to be "
                f"either. Drop it, or split this into separate --aliases values")
        key = generator.canonical_id_for(value)
        if not key or key in seen:
            continue
        seen.add(key)
        out.append(value)
    if len(out) > MAX_ALIASES:
        raise EntityError(
            f"{len(out)} aliases were given (max {MAX_ALIASES}) — every alias is a spelling that "
            f"silently reassigns mentions to this entity, so a long list is a merge decision "
            f"rather than a birth")
    return tuple(out)


def _clean_role(role) -> str:
    """One line about the entity, collapsed to one line and clipped — never a YAML escape.

    Held to `_YAML_UNSAFE` rather than to the name's whole forbidden set, and the constant carries
    the argument for why. The quote is the one that matters: `--role 'CEO, "the boss"'` is a
    plausible thing for a human to type, and interpolated raw it produces frontmatter PyYAML cannot
    parse, surfacing three commands later as `… declares no 'title'` — a message describing neither
    the cause nor the fix. `_yaml_str` is what makes that value survive verbatim; this refusal
    exists so the page is still safe if some future writer stops escaping.
    """
    value = " ".join(str(role or "").split())[:MAX_ROLE_CHARS]
    bad = sorted(_YAML_UNSAFE & set(value))
    if bad:
        raise EntityError(
            f"--role contains {', '.join(repr(c) for c in bad)}, which cannot appear in the "
            f"page's `role` field — it is written into the frontmatter, where those characters "
            f"delimit and escape the value rather than being part of it. Rephrase the line "
            f"without them (single quotes are fine)")
    return value


def _refuse_collisions(*, canonical_id: str, name: str, aliases, registry: Registry,
                       existing_pages) -> None:
    """The gate itself. Names WHICH input collided and WHICH entry it collided with.

    Ordered name -> id -> aliases, and the order is not cosmetic: the id is DERIVED from the name,
    so an exact name collision collides on both, and reporting it as `--id` would tell a steward
    their id was wrong when what actually already exists is the entity itself. Checking the name
    first makes the common case read as what it is; `--id` then only ever fires when a DIFFERENT
    name slugs onto a taken id, which is the case where the id really is the problem.
    """
    for label, value in [("--name", name), ("--id", canonical_id),
                         *[("an alias", alias) for alias in aliases]]:
        hit = registry.canonical_id(value)
        if not hit:
            continue
        entry = registry.entities.get(hit, {})
        listed = ", ".join(entry.get("aliases") or ()) or "none"
        raise CollisionError(
            f"{value!r} (given as {label}) already resolves to the registered entity {hit!r} "
            f"(name: {entry.get('name')}, type: {entry.get('type')}, aliases: {listed}). If this "
            f"is the same thing, point the capture at the existing entity instead of minting a "
            f"second one — requeue it, or answer its ask-back naming {entry.get('name')!r}. If it "
            f"genuinely is a different one, pick an id, name or alias that does not collide and "
            f"try again")

    # The FILE check, beside the registry check rather than folded into it. A page can exist while
    # the registry does not know it (drift, a hand-written page, a half-finished approval), and
    # that is exactly the `northwind-slides.md` next to `Northwind Group.md` shape — two files,
    # one identity, nothing refusing it. Case-insensitive because the knowledge repo's linter
    # treats duplicate basenames case-insensitively (macOS and Obsidian both resolve that way), so
    # a page differing only in case is already a contract violation there.
    wanted = f"{name}.md".lower()
    for relpath in existing_pages or ():
        if relpath.rsplit("/", 1)[-1].lower() == wanted:
            raise CollisionError(
                f"{relpath} already exists, so a page for {name!r} is already in the knowledge "
                f"repo even though {generator.REGISTRY_RELPATH} does not register it. That "
                f"disagreement is drift, not a free slot: run `{generator.FIX_COMMAND} --check` to "
                f"see it, and register or rename the existing page rather than writing a second "
                f"one beside it")


def recheck(proposal: Proposal, *, registry: Registry, existing_pages=()) -> None:
    """Re-run the gate for an ALREADY-VALIDATED proposal against a registry that has moved.

    `prepare` answers "may this identity exist, given what is registered right now". That answer
    has a shelf life: between it and the push, `origin/main` can gain an entity nobody had seen,
    and the commit that lands is judged against the registry that exists THEN. This is the same
    gate asked the same question a second time — same function, `_refuse_collisions`, so the two
    answers can never come from two implementations of "collides".

    Not a second `prepare`: the inputs were cleaned and the id derived on the first pass, and
    re-deriving them would let a validation change alter what the retry is even asking about. What
    is re-asked is exactly the part that depends on the world.

    The CALLER decides what `registry` and `existing_pages` mean, and for the retry path they mean
    "everything except this proposal's own entity" — by then the page is committed, so an
    unfiltered view would collide with itself.
    """
    _refuse_collisions(canonical_id=proposal.canonical_id, name=proposal.name,
                       aliases=proposal.aliases, registry=registry,
                       existing_pages=existing_pages)


# ── the page ──────────────────────────────────────────────────────────────────────────────────
def render_page(template: str, proposal: Proposal, *, today: str) -> str:
    """Materialize `ops/templates/entity.md` for this proposal.

    **The template is the source of truth and is read from the repo**, never reproduced here. That
    is the same rule the knowledge repo's own linter states about it ("templates in ops/templates/
    are the human-facing source of truth"), and it means an edit to the template — a new section, a
    reworded prompt — reaches minted pages without a platform release.

    Only the frontmatter is rewritten, line by line, exactly as `librarian.page._strip_keys` does
    it and for the same reason: a YAML round-trip would reformat the whole block (quoting, list
    style, comments) and this file is diffed by humans. The BODY is left as the template wrote it,
    with the placeholder title substituted — a new entity page is a stub a steward fills in, and
    inventing prose for it would be this tool asserting facts nobody checked.

    **Every value that came from a human goes through `_yaml_str`, none through an f-string.** That
    is the second half of the module docstring's argument: writing the frontmatter by hand is the
    right call for a file humans diff, but writing it by hand does NOT mean interpolating into it.
    What comes back out of this page is what the registry will say — so the writer owes the same
    guarantee a YAML dumper would give, and the three fields a steward authors get it.
    """
    front, body = _split(template)
    today = _clean_today(today)
    fields = {
        "type": PAGE_TYPE,
        "title": _yaml_str(proposal.name),
        "entity_type": proposal.entity_type,
        "role": _yaml_str(proposal.role),
        "status": PAGE_STATUS,
        "aliases": "[" + ", ".join(_yaml_str(a) for a in proposal.aliases) + "]",
        "created": today,
        "updated": today,
        "tags": f"[entity, {proposal.entity_type}]",
        # The page's OWN registry id — what the template's `entity:` comment promises ("THIS
        # PAGE'S OWN registry id, once minted") and what `views.skeleton.entity_own_page`'s
        # docstring asserts is true of every governed birth. Written explicitly rather than left
        # to the template's literal `[]`, because `[]` is not "no anchor": under the page contract
        # it reads as a checked, explicit company-wide scope, so omitting the key would not merely
        # leave the anchor blank, it would assert the wrong one — on the one page type whose whole
        # job is to BE an entity.
        "entity": f"[{_yaml_str(proposal.canonical_id)}]",
        "related": "[]",
        "sources": "[]",
    }
    rendered = _rewrite_frontmatter(front, fields)
    body = body.replace("<Entity Name>", proposal.name)
    return f"---\n{rendered}\n---\n{body}"


_PLACEHOLDER_PREFIX = "<"


def _yaml_str(value) -> str:
    """One double-quoted YAML scalar that reads back as exactly `value`.

    Hand-written rather than `yaml.dump`ed because this module rewrites the frontmatter LINE BY
    LINE (see `render_page`) and a dumper works on documents: it would reformat the block, drop the
    template's comments and reorder its keys. What is borrowed from the dumper is the only part
    that matters — the escaping contract — and it is small enough to be read and checked here.

    Three escapes, and the third is not decoration. `\\` and `"` are what close or extend the
    scalar. A CONTROL character is the quieter one: YAML 1.1's printable set excludes it, so PyYAML
    raises on the raw byte and the page becomes unparseable — the same *symptom* as an unescaped
    quote (`… declares no 'title'`, three commands away from its cause) from a different input.
    `--role` and `--name` collapse whitespace but not `\\x1b`, and an ESC is one paste away from a
    steward who copied a name out of a terminal.
    """
    out = ['"']
    for char in str(value):
        if char in ("\\", '"'):
            out.append("\\" + char)
        elif char < " " or char == "\x7f":
            out.append(f"\\x{ord(char):02x}")
        else:
            out.append(char)
    out.append('"')
    return "".join(out)


def _clean_today(today) -> str:
    """The `created`/`updated` value, refused unless it is a bare ISO date.

    The one field here that CANNOT be quoted: every hand-authored page in the knowledge repo writes
    `created: 2026-07-27` unquoted, so it is a YAML date, and `_yaml_str`ing it would silently
    change its type on minted pages only. A value that cannot be escaped has to be constrained
    instead — otherwise `--today` (an injectable clock, but still a flag) is a line-oriented write
    into the frontmatter, which is the same defect as the alias chain with a different door.
    """
    value = str(today or "").strip()
    if not _ISO_DATE_RE.match(value):
        raise EntityError(
            f"--today {value!r} is not a date — it is written into the page's `created` and "
            f"`updated` fields as a bare YAML date, so it must be exactly YYYY-MM-DD")
    return value


def _split(template: str) -> tuple[str, str]:
    if not template.startswith("---"):
        raise EntityError(
            f"{generator.ENTITIES_RELDIR}'s template (ops/templates/entity.md) has no frontmatter "
            f"block, so there is nothing to fill in — a new entity page is the template with its "
            f"identity fields written, and this one cannot be read")
    parts = template.split("\n")
    for i in range(1, len(parts)):
        if parts[i].strip() == "---":
            return "\n".join(parts[1:i]), "\n".join(parts[i + 1:])
    raise EntityError("ops/templates/entity.md has a frontmatter block that is never closed")


def _rewrite_frontmatter(front: str, fields: dict) -> str:
    """Replace each declared key's value in place; append the ones the template does not carry.

    In place, so the template's own key ORDER and its comments survive — a minted page that
    reorders the fields against every hand-authored one would make every future diff of that page
    noisier than it needs to be. Trailing comments (`status: developing  # seed|...`) are dropped
    on the keys this writes, because they are instructions to a human filling the template in and
    the value is now filled.
    """
    written, out = set(), []
    for line in front.split("\n"):
        key = line.split(":", 1)[0].strip() if ":" in line and not line[:1].isspace() else ""
        if key in fields and key not in written:
            out.append(f"{key}: {fields[key]}")
            written.add(key)
        else:
            out.append(line)
    for key, value in fields.items():
        if key not in written:
            out.append(f"{key}: {value}")
    return "\n".join(line for line in out if line.strip()).strip("\n")


def commit_message(proposal: Proposal, *, submission_id: int | None = None,
                   trailer: str = "") -> str:
    """The one commit that carries the page and the regenerated registry.

    Conventional-commit shaped like the librarian's own (`feat(<type>): <subject>`), so the
    knowledge repo's history reads in one dialect whoever wrote the commit. The capture is named
    when there is one: that line is how a reader of `git log` gets from an entity's birth back to
    the material that prompted it, which is the whole audit trail this flow exists to leave.

    **`trailer`** (e.g. `"Approved-by: steward@example.com"`), appended as its own paragraph when
    non-empty — ADR 030 D1's git trailer for a server-driven (App-authored) mint: `git log` answers
    "who approved this identity" with a named human even though the commit's own author line names
    the App. Empty by default, which is what keeps a steward's own `approve`/`create` commit
    byte-identical to what it always was — this parameter is additive, never a second dialect.
    """
    body = (f"Approved by a steward from capture #{submission_id}."
            if submission_id else "Created by a steward.")
    message = (f"feat(entity): add {proposal.name}\n\n{body}\n\n"
              f"Registry regenerated from {generator.ENTITIES_RELDIR}/ in the same commit.\n")
    if trailer:
        message += f"\n{trailer}\n"
    return message
